services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: capgemini
      POSTGRES_PASSWORD: capgemini
    ports:
      - '5432:5432'